# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
exposecontroller:
  exposecontroller:
    HTTP: "true"
    TLSACME: "false"
                
# disable monocular until the routing is fixed
monocular:
  enabled: false

      
docker-registry:
  enabled: false      
            
jenkins:
  Master:
    Image: "davidconde/jenkinsx-openshift"
    ImageTag: "0.0.1"
    ServiceAccountAnnotations: |
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
        {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}
    AuthorizationStrategyClass: "hudson.security.GlobalMatrixAuthorizationStrategy"
    AuthorizationStrategyAttributes:
    - name: "permission"
      value: "hudson.model.Computer.Configure:admin"
    - name: "permission"
      value: "hudson.model.Computer.Delete:admin"
    - name: "permission"
      value: "hudson.model.Hudson.Administer:admin"
    - name: "permission"
      value: "hudson.model.Hudson.Read:admin"
    - name: "permission"
      value: "hudson.model.Item.Build:admin"
    - name: "permission"
      value: "hudson.model.Item.Configure:admin"
    - name: "permission"
      value: "hudson.model.Item.Create:admin"
    - name: "permission"
      value: "hudson.model.Item.Delete:admin"
    - name: "permission"
      value: "hudson.model.Item.Read:admin"
    - name: "permission"
      value: "hudson.model.Item.Workspace:admin"
    - name: "permission"
      value: "hudson.model.Run.Delete:admin"
    - name: "permission"
      value: "hudson.model.Run.Update:admin"
    - name: "permission"
      value: "hudson.model.View.Configure:admin"
    - name: "permission"
      value: "hudson.model.View.Create:admin"
    - name: "permission"
      value: "hudson.model.View.Delete:admin"
    - name: "permission"
      value: "hudson.scm.SCM.Tag:admin"
    SecurityRealmClass: "hudson.security.HudsonPrivateSecurityRealm"
    SecurityRealmAttributes:
    - name: "disableSignup"
      value: "true"
    - name: "enableCaptcha"
      value: "false"
  Global:
    EnvVars:
      DOCKER_REGISTRY: "docker-registry.default.svc:5000"