apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: knative-git-user-pass
    mandatory: true
    properties:
    - name: username
      key: secret/data/jx/pipelineUser
      question: the pipeline username
      help: the user name used by pipelines running in Jenkins X
      generator: gitOperator.username
    - name: password
      key: secret/data/jx/pipelineUser
      question: the pipeline token or password
      help: the token or password used by pipelines running in Jenkins X
      generator: gitOperator.password
  - name: knative-docker-user-pass
    mandatory: true
    properties:
    - name: username
      question: Docker Registry username
      help: The username used to access the external docker registry
      defaultValue: admin
    - name: password
      question: Docker Registry password
      help: The password used to access the external docker registry
      generator: password
    - name: host
      question: Docker Registry host name
      help: The host name (with optional port) for the container registry
      defaultValue: docker.io
    - name: email
      question: Docker Registry email address
      help: The email address used in the docker config.json file for authenticating with the registry
      defaultValue: jenkins-x@googlegroups.com
