# https://github.com/jenkins-x/cd-indicators/blob/main/charts/cd-indicators/values.yaml

secrets:
  postgres:
    password:
      secretKeyRef:
        name: cd-indicators-postgresql-password

# embedded postgresql chart
# https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
postgresql:
  existingSecret: cd-indicators-postgresql-password
