apiVersion: gitops.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: jenkins-x-bucketrepo
    mandatory: true
    properties:
    - name: username
      question: bucket repository user name
      help: The username used to authenticate with the bucket repository
      defaultValue: admin
    - name: password
      question: bucket repository password
      help: The password to authenticate with the bucket repository
      minLength: 5
      maxLength: 41
      generator: password


